global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "app"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:8000"]
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]
